cmake_minimum_required(VERSION 3.16)
project(loop VERSION 1.0 LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(PkgConfig REQUIRED)
pkg_check_modules(GTK REQUIRED IMPORTED_TARGET gtk+-3.0)
add_library(audio STATIC src/audio.c)
target_include_directories(audio PUBLIC vendor)
target_compile_definitions(audio PUBLIC MA_NO_ENCODING MA_NO_GENERATION MA_NO_FLAC)
target_link_libraries(audio PUBLIC pthread dl m)
add_executable(loop src/main.cpp)
target_compile_options(loop PRIVATE -Wall -Wextra -Wpedantic)
target_link_libraries(loop PRIVATE audio PkgConfig::GTK)
install(TARGETS loop RUNTIME DESTINATION bin)
